plugins:
    - jekyll-remote-theme
    
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Pebble.js Docs
description: Revamped documentation for Pebble.js.

color-scheme: auto

favicon: true

navigation:
  - name: Home
    link: ./index.html
  - name: The Basics
    sublist:
      - name: Getting Started
        link: ./getting_started.html
      - name: Images
        link: ./images.html
      - name: Fonts
        link: ./fonts.html
      - name: Using Colors
        link: ./using_colors.html
      - name: Feature Detection
        link: ./feature_detection.html
  - name: API References
    sublist:
      - name: Require
        link: ./main/require.html
      - name: Pebble
        link: ./main/pebble.html
      - name: Fonts
        link: ./fonts.html
      - name: Using Colors
        link: ./using_colors.html
      - name: Feature Detection
        link: ./feature_detection.html
      - name: Getting Started
        link: ./getting_started.html
      - name: Images
        link: ./images.html
      - name: Fonts
        link: ./fonts.html
      - name: Using Colors
        link: ./using_colors.html
      - name: Feature Detection
        link: ./feature_detection.html
        
