plugins:
    - jekyll-remote-theme
    
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Pebble.js Docs
description: Revamped documentation for Pebble.js.

color-scheme: auto

favicon: true

navigation:
  - name: Home
    link: ./index.html
  - name: Getting Started
    sublist:
      - name: Image
        link: ./test.html
  - name: Another Page
    link: ./another-page.html
