plugins:
    - jekyll-remote-theme
    
remote_theme: kitian616/jekyll-text-theme

text_skin: dark
highlight_theme: tomorrow-night


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: pebble-dev/pebblejs
repository_tree: master

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
