plugins:
    - jekyll-remote-theme
    
remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: Pebble.js Docs
description: Revamped documentation for Pebble.js.

color-scheme: auto

# logo: /assets/img/<logo_file>

# favicon: true

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/pebble-dev
